#+TITLE:Public Health Surveillance Shortcourse \\GIS for surveillance 
#+AUTHOR: Ivan Hanigan
#+email: ivan.hanigan@anu.edu.au
#+LaTeX_CLASS: article
#+LaTeX_CLASS_OPTIONS: [a4paper]
#+LATEX_HEADER: \usepackage{verbatim}
#+LATEX_HEADER: \setlength{\parindent}{0in}
-----

* Background
In this demonstration we'll use the online working paper by Glynn (2011) at http://www.franklincenterhq.org/2541/geocoding-addresses-from-missouri-sex-offender-registry/
\cite{Glynn2011} and \cite{Glynn} to call Google's Geocoding API
\cite{Google} for a set of example individuals given their street,
city and state.  The example data are sourced from the Missouri Sex
Offender Registry. For further information see the `Action News'
article \cite{Kath2011} or the Economist \cite{TheEconomi2009}.
* R codes
The worked example does the data manipulations using the R statistical
analysis language http://www.r-project.org/. Download the R files from
the website http://dl.dropbox.com/u/7075452/PHsurveillance_overview.org and store in a working directory. 
\begin{comment}
 I used the package
ProjectTemplate to set up a directory called `analysis' which
automatically creates a `src' directory for source code files and a
`data' directory for data files.  The other directories are included
by default and have more esoteric functions that we will not use in
this example.
\end{comment}
#+name:R-init
#+begin_src R :session *R* :tangle analysis/transformations_overview.r :exports none :eval no
  if(!require(ProjectTemplate)) install.packages('ProjectTemplate');require(ProjectTemplate)
  # initialise project dir
  # create.project(project.name='analysis', minimal =TRUE)
 
#+end_src
* Download example data
The source of the data is at the bottom of this website \\ 
http://www.mshp.dps.mo.gov/MSHPWeb/PatrolDivisions/CRID/SOR/SORPage.html
#+name:download
#+begin_src R :session *R* :tangle analysis/src/download.r :exports none :eval no
  download.file(url='http://www.mshp.dps.mo.gov/MSHPWeb/PatrolDivisions/CRID/SOR/msor.zip',destfile = 'analysis/data/msor.zip',mode = 'wb')
  unzip(zipfile = 'analysis/data/msor.zip', exdir = 'analysis/data')
#+end_src

* Load and clean
Glynn has provided a downloadable source code file for cleaning the
data.  All we need to do manually is to open the Excel file and delete
the top 13 lines of summary information, after that deletion we saved
the data to a new Excel file named Missouri-Sex-Offenders.xls.  R
would now read this file.
#+name:Load
#+begin_src R :session *R* :tangle go.r :exports none :eval no
  setwd("~/PHSurveillanceShortcourse")
  oldwd<- getwd()
  download.file(url='http://cdn.watchdogmedia.org/national/computer-assisted-reporting/project/geocoding-and-distances/missouri-sex-offenders/Missouri-Sex-Offenders.R',destfile
  = 'analysis/src/Missouri-Sex-Offenders.r',mode = 'wb')
  # to run specific source files
  # list all files with
   dir('analysis/src',pattern='.r',full.names=T)
  # we could just source() this file and run all its contents however on inspection realise that the downloaded R file has a couple of edits to make by hand first, to reflect our working directory.
  source('analysis/src/Missouri-Sex-Offenders.r')
  
#+end_src

* Do geocoding
This step takes some time.  There is also the issue that Google restricts users to only geocoding 2500 addresses per day.  Therefore the full 12174 addresses would take 4.9 days to complete.
#+name:get.geocode
#+begin_src R :session *R* :tangle go.r :exports none :eval no
  
  download.file(url='http://cdn.watchdogmedia.org/national/computer-assisted-reporting/project/geocoding-and-distances/missouri-sex-offenders/GoogleGeocode.R',destfile = 'analysis/src/GoogleGeocode.r',mode = 'wb')
  dir('analysis/src',pattern='.r',full.names=T)
  # we could just source() this file and run all its contents however on inspection realise that the downloaded R file has a couple of edits to make by hand first, to reflect our working directory.
  source('analysis/src/GoogleGeocode.r')
  
#+end_src

#+name:do geocoding
#+begin_src R :session *R* :tangle go.r :exports none :eval no
  
  download.file(url='http://cdn.watchdogmedia.org/national/computer-assisted-reporting/project/geocoding-and-distances/missouri-sex-offenders/GoogleGeocodeMOSexOffenders.R',destfile = 'analysis/src/GoogleGeocodeMOSexOffenders.r',mode = 'wb')
  
 # we could just source() this file, but make edits by hand first
 # source('analysis/src/GoogleGeocodeMOSexOffenders.r')
  
#+end_src

* Check outputs

#+name:check-outputs
#+begin_src R :session *R* :tangle go.r :exports none :eval no
  # first line up the data
  #rm(d)
  if(!exists('d')) d <- read.table(file.path('analysis/data',"geocode-MO-offender-out.txt"), header=T)
  head(d)
  select <- (d$status == "OK") & (d$result.count > 0) & (d$state == 'Missouri')
  d <- d[select,]
  d$fuzzy <- (d$result.count > 1) | (d$location.type != "ROOFTOP")
  head(d)
  offender.data <- d
  
  # now make a map
  library(maps)
  png('offenders.png', res = 100)
  map("county", "Missouri", col="grey")
  mtext(paste("Missouri Sexual Offenders",Sys.Date()), adj=0, col="red")
  points(offender.data$lng, offender.data$lat,
  col=ifelse(offender.data$fuzzy, "palevioletred", "red"))
  dev.off()
  
#+end_src

An estimate of the precision of the geocode is given in the location\_type feild.  This stores additional data about the specified location. The following values are currently supported:
\begin{itemize}
\item ROOFTOP indicates that the returned result is a precise geocode for which we have location information accurate down to street address precision.
\item RANGE\_INTERPOLATED indicates that the returned result reflects an approximation (usually on a road) interpolated between two precise points (such as intersections). 
\item GEOMETRIC\_CENTER indicates that the returned result is the geometric center of a result such as a polyline (for example, a street) or polygon (region).
\item APPROXIMATE indicates that the returned result is approximate.
\end{itemize}

* Find a specific offender
From the article in the Economist \cite{TheEconomi2009} we know that Janet Allison was found guilty because she let her 15-year-old daughter have sex with a boyfriend she later married. But Ms Allison will ``spend the rest of her life publicly branded as a sex offender.'' So let's look her up.
#+name:check-outputs-2
#+begin_src R :session *R* :tangle go.r :exports none :eval no
 nrow(offender.data)
names(offender.data)
offender.data[1,]
which(offender.data$Name == 'ALLISON, JANET')

  
#+end_src
#+name:checked
#+begin_src R :session *R* :tangle go.r :exports results :eval no
  offender <- read.csv(file.path('analysis/data','msor-offender-master-file.csv'))
  offender[grep('ALLISON', offender$Name),c('Name','Address','Comments')]
#+end_src

#+results: checked
| ALLISON, CORD J    | 3655 PENNRIDGE DR APT 220 | CHILD MOLEST-2ND DEGREE                   |
| ALLISON, EARNEST E | 2737 US HWY 65            | DEVIATE SEXUAL ASSAULT                    |
| ALLISON, JOE E     | 22123 AUDRAIN RD 9318     | POSSESSION OF CHILD PORNOGRAPHY           |
| ALLISON, STEVEN L  | 10390 HWY D               | ENDANGERING WELFARE OF A CHILD-1ST DEGREE |
| HOPSON, ALLISON M  | 4258 ST LOUIS AVE         | RAPE                                      |

This person does not live in Missouri, but in Georgia.
* Put somebody on the map
#+name:identify
#+begin_src R :session *R* :tangle go.r :exports results :eval no
  print(offender[grep('AARON, JEFFERY W', offender$Name),c('Name','Address','Comments')])
#+end_src

#+results: identify
| AARON, JEFFERY W | 371 YEARGAN LN | SEXUAL ABUSE IN THE SECOND |

#+name:identified
#+begin_src R :session *R* :tangle go.r :exports none :eval no
offender.data[which(offender.data$Name == 'AARON, JEFFERY W'),]
offender[grep('AARON, JEFFERY W', offender$Name),c('Name','Address','Comments')]
png('offenderIdentified.png', res = 100)
map("county", "Missouri", col="grey")
mtext(paste("Missouri Sexual Offenders",Sys.Date()), adj=0, col="red")
points(offender.data$lng, offender.data$lat,
col=ifelse(offender.data$fuzzy, "palevioletred", "red"))
identified <- offender.data[which(offender.data$Name == 'AARON, JEFFERY W'),]
points(identified$lng, identified$lat,col='blue', pch = 16)

dev.off()

#+end_src
\begin{figure}[!h]
\centering
\includegraphics[width=\textwidth]{offenderIdentified.png}
\caption{offenderIdentified.png}
\label{fig:offenderIdentified.png}
\end{figure}
\clearpage
* Write the final(ish) data
To facilitate using the data in a GIS package we'll write these points out to a ESRI Shapefile.  The Shapefile is probably the most common format you find spatial data in; as Wikipedia points out it is `a (mostly) open specification for data interoperability among GIS software'.  The code also shows how to easily re-project the data into arbritrary coordinate systems (sometimes important for getting multiple data sources to relate) and we'll go for WGS84 as it is also common. 
#+name:finalishData
#+begin_src R :session *R* :tangle go.r :exports none :eval no
  # tools
  if(!require(rgdal)) install.packages('rgdal'); require(rgdal)
  epsg<-make_EPSG()
  
  # project as GDA94
  epsg[grep('GDA94',epsg$note),] 
  # find correct code is 4283
  d1 <- SpatialPointsDataFrame(coords = offender.data[,c('lng', 'lat')],
          data = offender.data,
          proj4string=CRS(epsg$prj4[epsg$code %in% '4283']))
  
  summary(d1)
  
  # reproject as WGS84, this is a trivial example. the difference will be miniscule.
  epsg[grep('WGS 84',epsg$note),]
  # yuck so many options,  figured out using google
  epsg[grep(4326,epsg$code),] 
  d2 <- spTransform(d1, CRS(epsg$prj4[grep(4326,epsg$code)]))
  summary(d2)
  
  # write out as projected shapefile
  writeOGR(d2,"test","test","ESRI Shapefile")
  
  
#+end_src

* Next steps
The worked examples on this website continue through the steps required to set up an interactive web map so that the surveillance system can be utilised by the general public \\
http://batchgeo.com/map/356612ae67bb92de8c91dd9fb7e27029.  

* References
\begin{comment}
\bibliographystyle{unsrt}
\bibliography{I:/references/library}
\end{comment}

\begin{thebibliography}{1}

\bibitem{Glynn2011}
Earl~F Glynn.
\newblock {Geocoding addresses from Missouri Sex Offender Registry: Computer
  Assisted Reporting.
  http://www.franklincenterhq.org/2541/geocoding-addresses-from-missouri-sex-offender-registry/}.
\newblock Technical report, Franklin Center for Government and Public
  Integrity, Bismarck, ND, 2011.

\bibitem{Glynn}
Earl~F Glynn.
\newblock {GoogleGeocode.R,
  http://cdn.watchdogmedia.org/national/computer-assisted-reporting/project/geocoding-and-distances/missouri-sex-offenders/GoogleGeocode.R}, 2010.

\bibitem{Google}
Google.
\newblock {Google Geocoding API,

  http://code.google.com/apis/maps/documentation/geocoding/index.html}.

\bibitem{Kath2011}
Ryan Kath.
\newblock {Loophole in law allows hundreds of Missouri sex offenders to live
  near church day cares,
  http://www.kshb.com/dpp/news/local\_news/investigations/loophole-in-law-allows-hundreds-of-missouri-sex-offenders-to-live-near-church-daycares}.
\newblock {\em KSHB NBC Action News}, 2011.

\bibitem{TheEconomi2009}
The Economist.
\newblock {America's unjust sex laws,
  http://www.economist.com/node/14165460?story\_id=14165460}.
\newblock {\em The Economist}, 2009.

\end{thebibliography}
